name: "Deploy WordPress to Server"
branding:
  icon: "upload-cloud"
  color: "blue"
description: "Deploy WordPress projects to a Server using SSH Gateway"
inputs:
  SSH_KEY_PRIVATE:
    description: "The private RSA key you will save in the Github Secrets"
    required: true
  SSH_REMOTE_HOST:
    description: "The SSH Host you will save in the Github Secrets"
    required: true
  PHP_LINT:
    description: "optional php syntax check"
    required: false
    default: false
  FLAGS: 
    description: "Optional flags for the deployment"
    required: true
    default: '-azvr --inplace --exclude=".*"'
  BRANCH: 
    description: "Source branch to deploy ENVIROMENT"
    required: true
    default: "PROD_BRANCH_HERE"
  ENVIROMENT:
    description: "Destination to deploy to WPE Prod"
    required: true
    default: "PROD_ENV_HERE"

runs:
  using: "docker"
  image: "Dockerfile"